### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by LucasArusiewicz** [matheus-s-arruda/Cognite#1]
Hey man, great plugin, I found it very interesting, I'm doing some tests with it, but for now I'm not using it in any project.

I would like to make some suggestions.

- Having a step-by-step text on how to use the plugin, something very simple and direct.

- The first step in using the plugin could be directly in the "Cognite editor" and have some buttons to create nodes and resources.

- Its usability could be more fluid if the editor was moved to the top bar of godot, being more centralized and using the entire editor screen. The [G-Kanban](https://github.com/H4x0r-000/gkanban) plugin does this for example.

 ![image](https://github.com/matheus-s-arruda/Cognite/assets/13992129/97daac4d-9b10-437f-ba09-982a79d4d6f1)

_Note: As there is no contribution guide yet, I ended up putting together some suggestions. I hope I can contribute to the plugin in the future 😊_

**Comment by matheus-s-arruda** [comment]
Thanks for the suggestions, I still intend to make some changes to the plugin and I will take these ideas into consideration.
