### ISSUE TITLE
Cannot trigger event from multiple states

### ISSUE THREAD

**Issue by EndersWilliam** [matheus-s-arruda/Cognite#2]
Really love the plugin so far and I'd love to use it for enemy ai, but it seems to be breaking down on me. 

I'm trying to extend the example graph in the readme with a Hunt state, pictured here:
![image](https://github.com/matheus-s-arruda/Cognite/assets/56558099/a2f12d2b-bdc9-44f9-b327-33b7a82b01a3)

I have a super simple script that calls `cognite_node.enemy_detected.emit()` along with `enemy_lost` and `chill` respectively. Everything works as expected, except for the transition from HUNT to COMBAT. Triggering `enemy_detected` while in the HUNT state does nothing.

Maybe I'm doing something wrong, would appreciate any insight.

I'm using `Godot 4.2 stable` and `Cognite 2.0`

**Comment by EndersWilliam** [comment]
nevermind! looks like it was fixed in [bug correction](https://github.com/matheus-s-arruda/Cognite/commit/eadd634a4211a53d7947fd8a1e7be43c5497987c) however that fix isn't included in the release zip

**Comment by matheus-s-arruda** [comment]
Hello friend, I really forgot to update the release to fix this bug, sorry for the inconvenience :D
